# Generated by Django 5.1.4 on 2025-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', 'XXXX_cleanup_duplicate_blobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='file_path',
            field=models.CharField(help_text='Original file path', max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='blob',
            unique_together={('sha1_hash', 'file_path')},
        ),
    ]
