# Generated by Django 5.1.4 on 2025-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='content',
            field=models.BinaryField(help_text='Base64 encoded content of the file', null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='parent_hash',
            field=models.CharField(blank=True, help_text='Hash of the parent commit', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='timestamp',
            field=models.DateTimeField(help_text='When the commit was created'),
        ),
    ]
