# Generated by Django 5.1.7 on 2025-10-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_alter_blob_file_path_alter_blob_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1_hash', models.CharField(help_text='SHA1 hash of the file content', max_length=40, unique=True)),
                ('compressed_data', models.BinaryField(help_text='zlib compressed file content')),
                ('size', models.PositiveIntegerField(help_text='Original file size in bytes')),
            ],
        ),
        migrations.CreateModel(
            name='GitTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1_hash', models.CharField(max_length=40, unique=True)),
                ('entries', models.JSONField(help_text='Dictionary of name->sha1_hash mappings')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.gittree')),
            ],
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.gitcommit')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.gittree')),
            ],
        ),
    ]
