# Generated by Django 5.1.4 on 2025-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_blob_content_commit_parent_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='blobs',
            field=models.ManyToManyField(help_text='Current files in the repository', related_name='repositories', to='data.blob'),
        ),
    ]
