# Generated by Django 5.1.7 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_gitblob_gittree_gitcommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='deleted_files',
            field=models.JSONField(blank=True, default=list, help_text='List of file paths that were deleted in this commit'),
        ),
    ]
