# Generated by Django 5.1.4 on 2025-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_repository_blobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='sha1_hash',
            field=models.CharField(help_text='SHA1 hash of the file content', max_length=40),
        ),
    ]
